export { default as MainMenu } from '../pages/main-menu.vue'
export { default as MainInput } from "../components/main-menu/main-inputLabel.vue"
export { default as MainVerticalNav } from "../components/main-menu/main-verticalNavigation.vue"
export { default as AddSpace } from '../pages/query-operation/add-space.vue'
export { default as DeleteSpace } from '../pages/query-operation/delete-space.vue'
export { default as ModifySpace } from '../pages/query-operation/modify-space.vue'
export { default as ModifyBuilding } from '../pages/query-operation/modify-building.vue'
export { default as NotFoundComponent } from "../pages/error.vue"
export { default as FloorMenu } from "../pages/floor-menu.vue"
export { default as FloorVerticalNav } from "../components/floor-menu/floor-verticalNavigation.vue"
export { default as SpaceMenu } from "../pages/space-menu.vue"
export { default as SpaceVerticalNav } from "../components/space-menu/space-verticalNavigation.vue"
